baseURL = 'https://buli-home.cn/'
defaultContentLanguage = 'zh-cn'
title = 'Buli Home'
theme = "FixIt"

[markup]
  defaultMarkdownHandler = "goldmark"
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"